### ISSUE TITLE
Allow bots to be configured per-repository

### ISSUE THREAD

**Issue by LegalizeAdulthood** [reviewboard/ReviewBot#12]
We have a large review board installation for multiple teams with multiple repositories.  We would like to use reviewbot on our team, but not all teams want the same level or types of reviews from a robot that our team.  Therefore, we'd like the admin interface to allow us to configure which reviewbots should be applied to which repo.  We're ok with multiple configurations of the same "bot" in order to get different settings for different teams.

**Comment by misery** [comment]
Should be possible with 1.0!
