### ISSUE TITLE
Timeout of 2 seconds in WorkerStatusView.get results in false negatives showing "No worker nodes found"

### ISSUE THREAD

**Issue by sammydre** [reviewboard/ReviewBot#19]
In views.py, there is the following code:

```
                reply = extension.celery.control.broadcast('update_tools_list',
                                                           payload=payload,
                                                           reply=True,
                                                           timeout=2)
```

If a worker node does not reply before the 2 second timeout, then for the purposes of the status shown under the extension configuration, the result will be "No worker nodes found".

In my testing, I was noticing my workers taking between 1.5s and 3.0s to reply. I think due to the fact that the worker checks for tool dependencies before replying, which can take a little time. In one case, I had a server always take longer than 2 seconds, meaning it would never show here, making me believe I had mis-configured the system.

I "fixed" the issue by changing the "timeout=2" to "timeout=10" here. This isn't a great fix, as now the webpage needs to wait 10 seconds before showing me the status of the connected workers. But it did now, at least, show the correct information.

**Comment by davidt** [comment]
Hey--would you mind filing this on https://hellosplat.com/s/beanbag/tickets/new/ ? I didn't realize that we still had issues turned on for this repo.
