### ISSUE TITLE
Option to "Not  adding comment if no problem found by reviewbot plugin"

### ISSUE THREAD

**Issue by PatrickZhao** [reviewboard/ReviewBot#8]
We  have just setup reviewbot to do cpp code checking in our team.
The tool is great!
One small problem found:
When one plugin (e.g. cpplint) dose not find any problem, it will still add one comment to reviewboard, which is a little annoying.
It would be better if there is one user option to disable comment when no problem found by a plugin.

Thank!

**Comment by misery** [comment]
Fixed for 1.0?
